# docker-compose for local development
# - `frontend` runs the Vite dev server (HMR)
# - `web` runs the FastAPI backend (uvicorn --reload)
# - `db` runs a Postgres instance for local testing

name: pyledger

services:
  web:
    build: .
    ports:
      - "${APP_EXT_PORT}:8000"
    environment:
      PYTHONUNBUFFERED: 1
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD_FILE: /run/secrets/db_password
    depends_on:
      - db
    secrets:
      - db_password


  db:
    image: postgres:18.1
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - db_data:/var/lib/postgresql

secrets:
  db_password:
    environment: DB_PASSWORD
volumes:
  db_data:
